"""estrutura inicial

Revision ID: 27fae97b832d
Revises: 
Create Date: 2026-10-07 11:16:50.239252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fae97b832d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imagens_s3_key'), ['s3_key'], unique=True)

    op.create_table('postagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('STORY', name='tipo_postagem'), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'AGENDADO', 'PROCESSANDO', 'PUBLICADO', 'ERRO', 'CANCELADO', name='status_postagem'), nullable=False),
    sa.Column('agendado_para', sa.DateTime(), nullable=True),
    sa.Column('chave_idempotencia', sa.String(length=36), nullable=False),
    sa.Column('instagram_container_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_media_id', sa.String(length=100), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('erro_codigo', sa.String(length=100), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('ultima_tentativa_em', sa.DateTime(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imagem_id'], ['imagens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_idempotencia')
    )
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postagens_agendado_para'), ['agendado_para'], unique=False)
        batch_op.create_index(batch_op.f('ix_postagens_imagem_id'), ['imagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postagens_status'), ['status'], unique=False)

    op.create_table('postagem_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postagem_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['postagem_id'], ['postagens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postagem_eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postagem_eventos_postagem_id'), ['postagem_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem_eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postagem_eventos_postagem_id'))

    op.drop_table('postagem_eventos')
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postagens_status'))
        batch_op.drop_index(batch_op.f('ix_postagens_imagem_id'))
        batch_op.drop_index(batch_op.f('ix_postagens_agendado_para'))

    op.drop_table('postagens')
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagens_s3_key'))

    op.drop_table('imagens')
    # ### end Alembic commands ###
