"""controle de erros e retentativas

Revision ID: 90d935c3a1bc
Revises: 27fae97b832d
Create Date: 2026-10-07 15:04:11.502878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d935c3a1bc'
down_revision = '27fae97b832d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fase_processamento', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('erro_tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('erro_recuperavel', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('proxima_tentativa_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processando_desde', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_postagens_processando_desde'), ['processando_desde'], unique=False)
        batch_op.create_index(batch_op.f('ix_postagens_proxima_tentativa_em'), ['proxima_tentativa_em'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postagens_proxima_tentativa_em'))
        batch_op.drop_index(batch_op.f('ix_postagens_processando_desde'))
        batch_op.drop_column('processando_desde')
        batch_op.drop_column('proxima_tentativa_em')
        batch_op.drop_column('erro_recuperavel')
        batch_op.drop_column('erro_tipo')
        batch_op.drop_column('fase_processamento')

    # ### end Alembic commands ###
